name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - run: npm run build

      - name: Check if build command changes source code
        run: git diff --name-only --exit-code

      - run: |
          git config --global user.email "contact@nodecg.dev"
          git config --global user.name "NodeCG Bot"
      - run: npm t

      - run: npx nyc report --reporter=text-lcov > coverage.lcov

      - name: Report code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.lcov

  release:
    runs-on: ubuntu-latest

    needs: build-test

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - run: npm ci

      - name: Prerelease
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          git config --global user.email "nodecg@example.com"
          git config --global user.name "nodecg"
          npx standard-version --prerelease next
          npm publish --tag next
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
